In [9]:

import re
import time
from difflib import get_close_matches
from itertools import islice

import pandas
import requests
from bs4 import BeautifulSoup
from openpyxl import load_workbook

start = time.time()
# assign url to variable and use requests to get html
print('Getting a list of all teams.')
url = 'https://www.teamrankings.com/nfl/teams/'
teams_page = requests.get(url)
teams = teams_page.content

# parse html with BeautifulSoup
soup = BeautifulSoup(teams, 'html.parser')

# scrap all team names and add to a dictionary
full_teams_list = {}
lst = soup.find_all('td', {'class': 'text-left'})

for item in lst:
    team_name = item.find('a').text
    # scrap url reference for team name (e.g., 'arizona-cardinals') and add to
    # dictionary
    url_ref = item.find('a')['href'][10:]
    full_teams_list[team_name] = url_ref
print('Done!')

def take(n, iterable):
    """Return first n items of the iterable as a list."""
    return list(islice(iterable, n))

# ugly but cant figure out why it's not scraping properly
del full_teams_list['Rankings']


#create list we will use below to grab stats
teams_list = []
url_ref_list = []

for teams in full_teams_list.items():
    teams_list.append(teams[0])
    url_ref_list.append(teams[1])

Getting a list of all teams.
Done!

In [69]:
## second part..

# build two lists of urls to scrap stats for each team
print('Building two lists of urls to parse')
stat_url_list = []
for url in url_ref_list:
    stat_url_list.append('https://www.teamrankings.com/nfl/team/' +
                         url + '/stats')
print('Done!')

print('Getting stats from teamrankings.com')
# create empty lists to hold stats
ypp = []
oYPP = []
qbsacked = []
sackpct = []

for stat in range(len(stat_url_list)):
    stats_page = requests.get(stat_url_list[stat])
    
    stats = stats_page.content

    soup1 = BeautifulSoup(stats, 'html.parser')


    numbers = soup1.find_all('td', {'class': 'nowrap'})
    s = []

    for number in numbers:
        s.append(number.text)
        
        
    try:
        ypp.append(float(s[13][:4]))
    except:
        ypp.append(0.00)
        
    try:
        oYPP.append(float(s[15][:4]))
    except:
        oYPP.append(0.00)
        
    try:
        qbsacked.append(float(s[77][:4]))
    except:
        qbsacked.append(0.00)
        
    try:
        sackpct.append(float(s[79][:4]))
    except:
        sackpct.append(0.00)

Building two lists of urls to parse
Done!
Getting stats from teamrankings.com

In [84]:
 def team_stats():
        offtable = {}
        offlist = []
        for i in range(len(full_teams_list)):
            team = teams_list[i]
            ypp_stat = ypp[i]
            oYPP_stat = oYPP[i]
            qbsacked_stat = qbsacked[i]
            sackpct_stat = sackpct[i]
            offtable.update (teamname = team, yppcol = ypp_stat, oYPPcol = oYPP_stat, qbsackedcol = qbsacked_stat, sackpctcol = sackpct_stat)
            offlist.append(dict(offtable))
            df = pandas.DataFrame(offlist)
        return df

In [85]:
team_stats()

                    teamname  yppcol  oYPPcol  qbsackedcol  sackpctcol
0          Arizona Cardinals     5.7      5.5         5.04       10.10
1            Atlanta Falcons     5.9      6.4         3.73        4.26
2           Baltimore Ravens     6.4      4.9        10.70        7.41
3              Buffalo Bills     6.6      6.0         6.56        6.56
4          Carolina Panthers     6.0      6.0         7.14        1.72
5              Chicago Bears     5.3      5.5         5.74        5.51
6         Cincinnati Bengals     4.2      5.5         9.03        4.76
7           Cleveland Browns     5.5      5.0         4.49        6.06
8             Dallas Cowboys     6.4      5.7         3.97        5.26
9             Denver Broncos     4.6      5.5        10.40        3.17
10             Detroit Lions     5.5      6.3         7.83        2.88
11         Green Bay Packers     6.9      6.6         1.85        7.84
12            Houston Texans     5.7      5.6        12.00        7.07
13        Indianapolis Colts     6.0      4.4         3.03       10.70
14      Jacksonville Jaguars     5.6      5.9         8.55        3.23
15        Kansas City Chiefs     5.7      6.1         2.47        8.45
16      Los Angeles Chargers     5.7      5.4         5.08        5.13
17          Los Angeles Rams     6.6      5.7         4.26        5.74
18         Las Vegas Raiders     5.8      6.4         4.76        2.91
19            Miami Dolphins     5.2      6.5         4.90        6.80
20         Minnesota Vikings     6.5      6.1         8.24        2.75
21      New England Patriots     6.1      6.2         5.21        5.26
22        New Orleans Saints     6.0      5.3         2.78        6.19
23           New York Giants     4.7      5.3         7.38        7.69
24             New York Jets     4.5      5.7         5.88        5.77
25       Philadelphia Eagles     4.5      4.8         7.69       10.50
26       Pittsburgh Steelers     5.6      4.8         4.39       12.30
27       San Francisco 49ers     5.9      4.8         7.69        4.59
28          Seattle Seahawks     6.5      6.6         8.04        3.12
29      Tampa Bay Buccaneers     5.4      4.7         4.39        9.68
30          Tennessee Titans     5.6      6.5         2.80        3.67
31  Washington Football Team     4.5      5.0         9.01       11.20